version: "3.8"

services:
  rails:
    restart: "no"
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/rails
      - ruby31:/usr/local/bundle
      - histfile:/histfile
    environment:
      - TZ=Asia/Tokyo
      - HISTFILE=/histfile/.bash_history
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.1.2"
    ports:
      - "3000:3000"
    command: "bundle exec puma"

volumes:
  ruby31:
  histfile:
